on:
  push:
  release:
    types: [released]

env:
  DOCKER_TAG: ghcr.io/${{ github.repository }}
  VERSION: ${{ github.ref_name }}

jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        tags: ${{ env.DOCKER_TAG }}:${{ env.VERSION }},${{ env.DOCKER_TAG }}:latest
        pull: true
        platforms: linux/arm64
        push: ${{ github.event_name == 'release' }}
        file: etc/docker/Dockerfile.triton-jetpack-focal
  module:
    needs: [container]
    # todo: remove concurrency group once APP-2549 is fixed
    concurrency: no-simultaneous-upload-${{ github.ref_name }}-${{ github.run_number }}
    strategy:
      matrix:
        platform: [arm64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        TAG=$DOCKER_TAG:$VERSION make -f Makefile.module module.tar.gz
    - uses: viamrobotics/upload-module@main
      if: github.event_name == 'release'
      with:
        module-path: module.tar.gz
        platform: linux/${{ matrix.platform }}
        version: ${{ env.VERSION }}
        cli-config-secret: ${{ secrets.cli_config }}
